/**
 * Built-in Curated Deliberation Templates (Phase 3)
 * High-fidelity topologies with domain-specific personas, protocols, and policies.
 */

import { DeliberationTemplate } from './types.ts';

export const BUILT_IN_TEMPLATES: DeliberationTemplate[] = [
  {
    id: 'tpl-distributed-rfc',
    title: 'Distributed Systems RFC & Consensus Review',
    description: 'Deep architectural debate on distributed state replication, CAP trade-offs, write quorums, and network partition resilience.',
    category: 'architecture',
    tags: ['Architecture', 'Consensus', 'Raft', 'High-Throughput'],
    goal: 'Design a globally distributed event-streaming backbone that guarantees strict FIFO ordering within partitions, survives 2 node losses in a 5-node cluster, and minimizes cross-region write latency.',
    suggestedProtocol: 'debate',
    speakerPolicy: 'moderator-directed',
    terminationPolicy: 'moderator-conclusion',
    maxRounds: 6,
    agents: [
      {
        name: 'Distributed Systems Architect',
        role: 'participant',
        provider: 'mock',
        model: 'claude-3-5-sonnet',
        rolePrompt: 'Senior Distributed Systems Architect. Prioritize composability, linearizable consistency where strictly needed, append-only logs, and decoupled partitions. Challenge complex two-phase commit designs.',
        temperature: 0.6,
        maxOutputTokens: 1024,
        contextBudget: 8192,
        timeoutSettings: { firstTokenMs: 10000, totalMs: 30000 },
        visualIdentity: { color: '#0284c7' },
      },
      {
        name: 'Infrastructure SRE Lead',
        role: 'participant',
        provider: 'mock',
        model: 'llama3.2',
        rolePrompt: 'Staff Site Reliability Engineer. Focus on operational realities: disk IOPS saturation, mean-time-to-recovery (MTTR), split-brain scenarios during rolling upgrades, and monitoring telemetry.',
        temperature: 0.5,
        maxOutputTokens: 800,
        contextBudget: 8192,
        timeoutSettings: { firstTokenMs: 10000, totalMs: 30000 },
        visualIdentity: { color: '#10b981' },
      },
      {
        name: 'Security & Integrity Officer',
        role: 'participant',
        provider: 'mock',
        model: 'gpt-4o',
        rolePrompt: 'Principal Security Architect. Enforce zero-trust node authentication (mTLS), tamper-evident cryptographic log chaining, and prevent data leakage across tenant namespaces.',
        temperature: 0.4,
        maxOutputTokens: 800,
        contextBudget: 8192,
        timeoutSettings: { firstTokenMs: 10000, totalMs: 30000 },
        visualIdentity: { color: '#f59e0b' },
      },
      {
        name: 'Technical Arbiter',
        role: 'moderator',
        provider: 'mock',
        model: 'gemini-2.5-pro',
        rolePrompt: 'Discussion Arbiter. Synthesize competing trade-offs, identify unresolved assumptions, keep the debate on consensus durability, and extract formal decisions to the blackboard.',
        temperature: 0.2,
        maxOutputTokens: 600,
        contextBudget: 8192,
        timeoutSettings: { firstTokenMs: 8000, totalMs: 25000 },
        visualIdentity: { color: '#8b5cf6' },
      },
    ],
  },
  {
    id: 'tpl-threat-modeling',
    title: 'Adversarial Threat Modeling & Zero-Trust Audit',
    description: 'Red-team vs Blue-team adversarial stress-testing of cloud infrastructure, IAM privileges, and token lifecycles.',
    category: 'security',
    tags: ['Security', 'Red-Team', 'Threat-Model', 'Zero-Trust'],
    goal: 'Audit an internal developer platform authentication service for privilege escalation, token replay, SSRF via webhooks, and unauthenticated metadata exposure.',
    suggestedProtocol: 'red-team',
    speakerPolicy: 'moderator-directed',
    terminationPolicy: 'moderator-conclusion',
    maxRounds: 5,
    agents: [
      {
        name: 'Red Team Infiltrator',
        role: 'participant',
        provider: 'mock',
        model: 'claude-3-5-sonnet',
        rolePrompt: 'Offensive Security Researcher. Look for unvalidated redirect URIs, JWT algorithm confusion (none/HS256 vs RS256), timing attacks, and blind SSRF vulnerabilities. Propose concrete exploit chains.',
        temperature: 0.7,
        maxOutputTokens: 1000,
        contextBudget: 8192,
        timeoutSettings: { firstTokenMs: 10000, totalMs: 30000 },
        visualIdentity: { color: '#ef4444' },
      },
      {
        name: 'Blue Team Hardener',
        role: 'participant',
        provider: 'mock',
        model: 'gpt-4o',
        rolePrompt: 'Defensive Infrastructure Engineer. Propose hardened mitigation: DPoP (RFC 9449), ephemeral short-lived tokens, egress firewall filters, and strict cryptographic nonce verification.',
        temperature: 0.5,
        maxOutputTokens: 800,
        contextBudget: 8192,
        timeoutSettings: { firstTokenMs: 10000, totalMs: 30000 },
        visualIdentity: { color: '#3b82f6' },
      },
      {
        name: 'Security Arbiter',
        role: 'moderator',
        provider: 'mock',
        model: 'gemini-2.5-pro',
        rolePrompt: 'CISO / Security Arbiter. Evaluate risk severity (CVSS), reject unproven defensive claims, and document actionable defensive controls on the shared blackboard.',
        temperature: 0.2,
        maxOutputTokens: 500,
        contextBudget: 8192,
        timeoutSettings: { firstTokenMs: 8000, totalMs: 25000 },
        visualIdentity: { color: '#9333ea' },
      },
    ],
  },
  {
    id: 'tpl-pre-mortem',
    title: 'Production Incident Pre-Mortem & Safeguards',
    description: 'Assume the upcoming major deployment fails catastrophically 6 months from now, working backwards to eliminate latent root causes.',
    category: 'reliability',
    tags: ['SRE', 'Pre-Mortem', 'Resilience', 'Post-Mortem'],
    goal: 'We are launching a real-time collaborative workspace to 500,000 daily active users. Fast forward 6 months: the database crashed, websocket brokers hung, and user edits were lost. Why did it happen?',
    suggestedProtocol: 'pre-mortem',
    speakerPolicy: 'round-robin',
    terminationPolicy: 'max-rounds',
    maxRounds: 4,
    agents: [
      {
        name: 'Database Reliability Lead',
        role: 'participant',
        provider: 'mock',
        model: 'llama3.2',
        rolePrompt: 'Database Reliability Specialist. Identify connection pool exhaustion, unbounded WAL log growth, vacuum stalls under heavy writes, and lock escalations during schema migrations.',
        temperature: 0.6,
        maxOutputTokens: 800,
        contextBudget: 8192,
        timeoutSettings: { firstTokenMs: 10000, totalMs: 30000 },
        visualIdentity: { color: '#d97706' },
      },
      {
        name: 'Realtime Transport Engineer',
        role: 'participant',
        provider: 'mock',
        model: 'gemini-2.5-flash',
        rolePrompt: 'WebSocket & Networking Specialist. Detail socket reconnect storms, heartbeat thrashing, memory leaks in socket buffers, and backpressure failures.',
        temperature: 0.6,
        maxOutputTokens: 800,
        contextBudget: 8192,
        timeoutSettings: { firstTokenMs: 10000, totalMs: 30000 },
        visualIdentity: { color: '#059669' },
      },
      {
        name: 'Incident Commander',
        role: 'moderator',
        provider: 'mock',
        model: 'gemini-2.5-pro',
        rolePrompt: 'Incident Commander. Facilitate the post-mortem inquest, prevent finger-pointing, focus on structural systemic vulnerabilities, and extract preventive controls to the blackboard.',
        temperature: 0.2,
        maxOutputTokens: 500,
        contextBudget: 8192,
        timeoutSettings: { firstTokenMs: 8000, totalMs: 25000 },
        visualIdentity: { color: '#7c3aed' },
      },
    ],
  },
  {
    id: 'tpl-ai-stack',
    title: 'AI/ML Model & Inference Stack Selection',
    description: 'Blind-first Delphi evaluation of local LLMs vs hosted frontier APIs for cost, latency, and privacy compliance.',
    category: 'strategy',
    tags: ['AI-Stack', 'Local-LLM', 'Frontier-Models', 'Cost-Optimization'],
    goal: 'Select the production inference stack for an enterprise multi-agent code reviewer: evaluate running Ollama/vLLM locally on premises vs cloud APIs (Claude 3.5, Gemini 2.5) for cost, latency, and IP protection.',
    suggestedProtocol: 'blind-first',
    speakerPolicy: 'moderator-directed',
    terminationPolicy: 'moderator-conclusion',
    maxRounds: 5,
    agents: [
      {
        name: 'Inference Performance Specialist',
        role: 'participant',
        provider: 'mock',
        model: 'llama3.2',
        rolePrompt: 'Machine Learning Infrastructure Engineer. Focus on tokens/sec per GPU, TTFT (time-to-first-token), vLLM continuous batching throughput, and hardware capex vs opex.',
        temperature: 0.5,
        maxOutputTokens: 800,
        contextBudget: 8192,
        timeoutSettings: { firstTokenMs: 10000, totalMs: 30000 },
        visualIdentity: { color: '#2563eb' },
      },
      {
        name: 'Data Privacy & IP Counsel',
        role: 'participant',
        provider: 'mock',
        model: 'gpt-4o',
        rolePrompt: 'Corporate Data Privacy and IP Counsel. Analyze vendor terms of service, zero-data-retention guarantees, data residency compliance (GDPR/HIPAA), and customer IP indemnity.',
        temperature: 0.4,
        maxOutputTokens: 800,
        contextBudget: 8192,
        timeoutSettings: { firstTokenMs: 10000, totalMs: 30000 },
        visualIdentity: { color: '#dc2626' },
      },
      {
        name: 'Evaluation Moderator',
        role: 'moderator',
        provider: 'mock',
        model: 'gemini-2.5-pro',
        rolePrompt: 'Technical Moderator. First collect independent blind estimates, reconcile disparities in cost projections, and record validated decisions on the blackboard.',
        temperature: 0.2,
        maxOutputTokens: 500,
        contextBudget: 8192,
        timeoutSettings: { firstTokenMs: 8000, totalMs: 25000 },
        visualIdentity: { color: '#4f46e5' },
      },
    ],
  },
];
